class HelpSection():
    def start(self):
        print()
        print('- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -', end = '')
        print('\n|                                                          |', end = '')
        print('\n|  Program se sastoji iz nekoliko sekcija:                 |', end = '')
        print('\n|                                                          |', end = '')
        print('\n|      1.) Generator prostih brojeva                       |', end = '')
        print('\n|          * Koristi se za generisanje prozvoljnih prostih |', end = '')
        print('\n|            brojeva zadate duzine.                        |', end = '')
        print('\n|                                                          |', end = '')
        print('\n|      2.) Inicijalizator RSA sistema                      |', end = '')
        print('\n|          * Za zeljenu duzinu brojeva, inicijalizuje RSA  |', end = '')
        print('\n|            sistem. Ovo ukljucuje trazenje para koji cini |', end = '')
        print('\n|            javni kljuc, kao i trazenje privatnog kljuca. |', end = '')
        print('\n|                                                          |', end = '')
        print('\n|      3.) Enkriptor                                       |', end = '')
        print('\n|          * Za dati podatak i par koji cini javni kljuc   |', end = '')
        print('\n|            vrsi enkripciju.                              |', end = '')
        print('\n|          * Podatak koji enkriptujemo moze biti unijet sa |', end = '')
        print('\n|            standardnog ulaza ili procitan iz datoteke,   |', end = '')
        print('\n|          * Enkriptovan sadrzaj se stampa na standardni   |', end = '')
        print('\n|            izlaz.                                        |', end = '')
        print('\n|          * Enkriptovani sadrzaj se moze sacuvati unutar  |', end = '')
        print('\n|            naznacene datoteke.                           |', end = '')
        print('\n|                                                          |', end = '')
        print('\n|      3.) Dekriptor                                       |', end = '')
        print('\n|          * Za dati podatak i privatni kljuc vrsi         |', end = '')
        print('\n|            dekripciju.                                   |', end = '')
        print('\n|          * Podatak koji dekriptujemo moze biti unijet sa |', end = '')
        print('\n|            standardnog ulaza ili procitan iz datoteke.   |', end = '')
        print('\n|          * Dekriptovani sadrzaj se stampa na standardni  |', end = '')
        print('\n|            izlaz.                                        |', end = '')
        print('\n|          * Dekriptovani sadrzaj se moze sacuvati unutar  |', end = '')
        print('\n|            naznacene datoteke.                           |', end = '')
        print('\n|                                                          |', end = '')
        print('\n- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -\n')
